jenkins:
  ports:
  - 9001:8080/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: 121.199.10.99:81/jenkins:1.1
  volumes:
  - /var/lib/docker/:/var/lib/docker/
  - /var/run/docker.sock:/var/run/docker.sock
  - /usr/bin/docker:/usr/bin/docker
  - /lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
  privileged: true
  stdin_open: true
gitlab:
  ports:
  - 9004:443/tcp
  - 9003:80/tcp
  - 9002:22/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: gitlab.youruncloud.com
  image: 121.199.10.99:81/gitlab/gitlab-ce
  volumes:
  - /srv/gitlab/config:/etc/gitlab
  - /srv/gitlab/logs:/var/log/gitlab
  - /srv/gitlab/data:/var/opt/gitlab
  stdin_open: true
