Nginx-HC-port80:
  ports:
   - 10001:80/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: 121.199.10.99:81/nginx:error
  stdin_open: true
Nginx-HC-http-respond:
  ports:
   - 10002:80/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: 121.199.10.99:81/nginx
  stdin_open: true
